about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.IndexView.as_view(), name='about'),
]

articles/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
     path('', views.post_list, name='post_list'),
     path('post/<int:pk>/', views.post_detail, name='post_detail'),
     path('post/new/', views.post_new, name='post_new'),
     path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

backoffice/urls.py
from django.urls import path

from . import views

app_name = 'backoffice'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.IndexView.as_view(), name='contact'),

]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('backoffice/', include('backoffice.urls')),
    path('contact/', include('contact.urls')),
    path('about/', include('about.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

about/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    # photo = models.ImageField(upload_to='images')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

backoffice/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.question_text

contact/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

about/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone



class IndexView(generic.ListView):
    template_name = 'about/about.html'


    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """

articles/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.urls import reverse
from .models import Post
from django.views import generic
from .forms import PostForm
from django.shortcuts import redirect
from django.http import HttpResponse


def post_list(request):
      posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
      return render(request, 'articles/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'articles/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'articles/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'articles/post_edit.html', {'form': form})

backoffice/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'backoffice/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'backoffice/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'backoffice/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'backoffice/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('backoffice:results', args=(question.id,)))

contact/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone



class IndexView(generic.ListView):
    template_name = 'contact/contact.html'


    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """

homepage/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone



class IndexView(generic.ListView):
    template_name = 'homepage/index.html'


    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """

about/templates/about/about.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Sergey Pozhilov (GetTemplate.com)">

	<title>JM-Blog - A propos</title>

	<link rel="shortcut icon" href="../static/about/images/gt_favicon.png">

	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="../static/about/css/bootstrap.min.css">
	<link rel="stylesheet" href="../static/about/css/font-awesome.min.css">

	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="../static/about/css/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="../static/about/css/main.css">

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="../static/about/js/html5shiv.js"></script>
	<script src="../static/about/js/respond.min.js"></script>
	<![endif]-->

</head>

<body>
<!-- Fixed navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
      <div class="navbar-header">
        <!-- Button for smallest screens -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <!-- <a class="navbar-brand" href="index.html"><img src="assets/images/logo.png" alt="Progressus HTML5 template">   3 Delta </a> -->
        <a class="navbar-brand" href="{% url 'homepage:index' %}"> JM-Blog </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li><a href="{% url 'homepage:index' %}">Homepage</a></li>
			<li><a href="/articles">Articles</a></li>
            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
          <li  class="active"><a href="{% url 'about:about' %}">A propos</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/articles">Articles</a></li>
              <li class="active"><a href="">Portfolio</a></li>
            </ul>
          </li>

          <li><a class="btn" href="signin.html">Se Connecter / S'enregistrer</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <!-- /.navbar -->

	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="{% url 'homepage:index' %}">Homepage</a></li>
			<li class="active">A propos</li>
		</ol>

		<div class="row">

			<!-- Article right content -->
			<article class="col-sm-12 maincontent">
				<br>
				<br>
				<center><img src="../static/about/images/3Delta.jpg" alt="" class="img-rounded mx-auto d-block" width="300" > </center>
				<br>
				<center><p>Website Version : Alpha 0.1 Janvier 2021</p></center>
				<center><p>Design conçu par : <a href="http://gettemplate.com/" rel="designer">gettemplate</a></p></center>
				<center><p>Back-end et adaptations du design par : <a href="{% url 'about:about' %}">Michel Jonathan</a></p></center>
				<center><p>Langages & Framework's utiliser: Python, Django, Postgresql, HTML, CSS, Javascript, Github, Pythonanywhere.</p> </center>
				<center><p>N'hésitez pas à nous contacter <a href="{% url 'contact:contact' %}">ici</a> si vous rencontrer des bugs !</p></center>
				<center><p>Le site 3Delta est en cours de développement, ce qui signifie que la version d'aurjourd'hui est susceptible d'évoluer afin d'y implémenter des fonctionnalités pour de futurs besoins.</p></center>

			</article>
			<!-- /Article -->
            	<!-- Article left content -->
			<article class="col-sm-12 maincontent">

				<center><h3>A propos de Michel Jonathan :</h3></center>
                <br>
				<center><img src="../static/about/images/about_jonathan_profil.png" alt="" class="img-rounded" width="300" ></center>
				<br>
				<center><p>Lorsque j'etait un très jeune enfant, mon parrain moi même et son fils, nous levions la nuit quand la mamie était endormi, pour jouer à la Nintendo et la Sega. Coca à la main et biberon chargé, nous faisions des nocturnes en avalant quantités de chips et pixels. A cet époque j’était déjà absorber par l’écran et les vieilles couleurs de jeux vidéos aux lueurs du tube cathodique et de la lune qui ne manquer pas de taillé nos cernes de geeks. Un peu plus tard , nous faisions l’acquisition d’un Ordinateur équipé du tout nouveau Système d’exploitation à la mode, windows 3.1, et donc nos premières aventures avec les jeux vidéos PC et les disquettes ne manquèrent pas de me scotché. J’ai eu l’opportunité de parcrourir différents systèmes et machines depuis et jusqu’à nos jours, qui lorsque, tomber en panne, ayant peu de moyens, nous partageons encore des missions sauvetage afin de réparer et étancher notre soif d’informatiques. A l’âge de 30 ans, depuis mes premiers pas en tant que PAREN sélectionnée pour parcticiper à la formation du WAGON je ne cesse de m’exercé à codé tout type de projets personnelle et concrétise mes passions acquise enfant. Je remercie Mathieu Bonfils @Le Wagon et Emmanuelle Erasquero @SIMPLON qui m’ont permis cette reconversion professionnelle. Je souhaite prendre plus d’assurance dans le domaine du développement, j’expérimente plusieurs langages par passion et curiosité. Cela me permet de comprendre ce que j’aime sans pour autant devoir tiré un trait sur des expériences passé, qui mise bout a bout m’aideront a concrétisé une passion que j’ai depuis toujours.</p></center>
				<br>
			</article>
			<!-- /Article -->



		</div>
	</div>	<!-- /container -->




	<footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">

					<div class="col-md-3 widget">
						<h3 class="widget-title">Contactez nous</h3>
						<div class="widget-body">
								<a href="{% url 'contact:contact' %}">Contact</a><br>
								<br>
								<a href="{% url 'homepage:index' %}">Website</a><br>
							</p>
						</div>
					</div>

					<div class="col-md-3 widget">
						<h3 class="widget-title">Suivez nous</h3>
						<div class="widget-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								<a href=""><i class="fa fa-dribbble fa-2"></i></a>
								<a href=""><i class="fa fa-github fa-2"></i></a>
								<a href=""><i class="fa fa-facebook fa-2"></i></a>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<h3 class="widget-title">Commentaires d'usages</h3>
						<div class="widget-body">
							<p>Veillez à respecter le(s) destinataire(s) de vos messages.</p>
							<p>Nous sommes tout à fait conscients que de potentielles erreurs peuvent se glisser au sein du site, mais votre avis compte à partir du moment qu'il est constructif et bienveillant.</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="{% url 'homepage:index' %}">Homepage</a> |
								<a href="{% url 'about:about' %}">A propos</a> |
								<a href="{% url 'contact:contact' %}">Contact</a> |
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2020,Made by <a href="{% url 'about:about' %}">Michel Jonathan</a>. Designed by <a href="http://gettemplate.com/" rel="designer">gettemplate</a>
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

	</footer>







	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="../static/about/js/headroom.min.js"></script>
	<script src="../static/about/js/jQuery.headroom.min.js"></script>
	<script src="../static/about/js/template.js"></script>

</body>
</html>

articles/templates/articles/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Sergey Pozhilov (GetTemplate.com)">

	<title>JM-Blog - Articles </title>

	<!-- <link rel="shortcut icon" href="../static/articles/images/gt_favicon.png"> -->
	<link rel="shortcut icon" href="{% static 'articles/images/gt_favicon.png' %}">

	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<!-- <link rel="stylesheet" href="../static/articles/css/bootstrap.min.css"> -->
	<link rel="stylesheet" href="{% static 'articles/css/bootstrap.min.css' %}">

	<!-- <link rel="stylesheet" href="../static/articles/css/font-awesome.min.css"> -->
	<link rel="stylesheet" href="{% static 'articles/css/font-awesome.min.css' %}">

	<!-- Custom styles for our template -->
	<!-- <link rel="stylesheet" href="../static/articles/css/bootstrap-theme.css" media="screen" > -->
	<link rel="stylesheet" href="{% static 'articles/css/bootstrap-theme.css' %}" media="screen" >

	<link rel="stylesheet" href="{% static 'articles/css/articles.css' %}">
	<link rel="stylesheet" href="{% static 'articles/css/main.css' %}">

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9] -->
	<!-- <script src="../static/articles/js/html5shiv.js"></script> -->
	<script src="{% static 'articles/js/html5shiv.js' %}"></script>
	<!-- <script src="../static/articles/js/respond.min.js"></script> -->
	<script src="{% static 'articles/js/respond.min.js' %}"></script>
	<![endif]-->

</head>

<body>

<!-- Fixed navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
      <div class="navbar-header">
        <!-- Button for smallest screens -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <!-- <a class="navbar-brand" href="index.html"><img src="assets/images/logo.png" alt="Progressus HTML5 template">   3 Delta </a> -->
        <a class="navbar-brand" href="{% url 'homepage:index' %}"> JM-Blog </a>
		  	{% if user.is_authenticated %}
			<a href="{% url 'post_new' %}" class="top-menu glyphicon glyphicon-plus"> EDIT</a>
			{% endif %}
      </div>

      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">

          <li><a href="{% url 'homepage:index' %}">Homepage</a></li>
			<li class="active"><a href="/articles">Articles</a></li>
            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
          <li><a href="{% url 'about:about' %}">A propos</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/articles">Articles</a></li>
              <li class="active"><a href="">Portfolio</a></li>
            </ul>
          </li>

          <li><a class="btn" href="signin.html">Se Connecter / S'enregistrer</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <!-- /.navbar -->

<header id="head" class="secondary"></header>

<!-- container -->
<div class="container">

	<ol class="breadcrumb">
		<li><a href="{% url 'homepage:index' %}">Homepage</a></li>
		<li class="active">Articles</li>
	</ol>

	<div class="row">


	</div>
</div>	<!-- /container -->
<br>

<div class="content container">
	<div class="row">
		<div class="col-md-12">
			{% block content %}
			{% endblock %}
		</div>
	</div>
</div>


<footer id="footer" class="top-space">

	<div class="footer1">
		<div class="container">
			<div class="row">

				<div class="col-md-3 widget">
					<h3 class="widget-title">Contactez nous</h3>
					<div class="widget-body">
						<a href="{% url 'contact:contact' %}">Contact</a><br>
						<br>
						<a href="{% url 'homepage:index' %}">Website</a><br>
						</p>
					</div>
				</div>

				<div class="col-md-3 widget">
					<h3 class="widget-title">Suivez nous</h3>
					<div class="widget-body">
						<p class="follow-me-icons">
							<a href=""><i class="fa fa-twitter fa-2"></i></a>
							<a href=""><i class="fa fa-dribbble fa-2"></i></a>
							<a href=""><i class="fa fa-github fa-2"></i></a>
							<a href=""><i class="fa fa-facebook fa-2"></i></a>
						</p>
					</div>
				</div>

				<div class="col-md-6 widget">
					<h3 class="widget-title">Commentaires d'usages</h3>
					<div class="widget-body">
						<p>Veillez à respecter le(s) destinataire(s) de vos messages.</p>
						<p>Nous sommes tout à fait conscients que de potentielles erreurs peuvent se glisser au sein du site, mais votre avis compte à partir du moment qu'il est constructif et bienveillant.</p>
					</div>
				</div>

			</div> <!-- /row of widgets -->
		</div>
	</div>

	<div class="footer2">
		<div class="container">
			<div class="row">

				<div class="col-md-6 widget">
					<div class="widget-body">
						<p class="simplenav">
							<a href="{% url 'homepage:index' %}">Homepage</a> |
							<a href="{% url 'about:about' %}">A propos</a> |
							<a href="{% url 'contact:contact' %}">Contact</a> |
						</p>
					</div>
				</div>

				<div class="col-md-6 widget">
					<div class="widget-body">
						<p class="text-right">
							Copyright &copy; 2020,Made by <a href="{% url 'about:about' %}">Michel Jonathan</a>. Designed by <a href="http://gettemplate.com/" rel="designer">gettemplate</a>
						</p>
					</div>
				</div>

			</div> <!-- /row of widgets -->
		</div>
	</div>

</footer>


<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<!-- <script src="../static/articles/js/headroom.min.js"></script> -->
<script src="{% static 'articles/js/headroom.min.js' %}"></script>
<!-- <script src="../static/articles/js/jQuery.headroom.min.js"></script> -->
<script src="{% static 'articles/js/jQuery.headroom.min.js' %}"></script>
<!-- <script src="../static/articles/js/template.js"></script> -->
<script src="{% static 'articles/js/template.js' %}"></script>

</html>

articles/templates/articles/post_detail.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
              {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
     <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
{% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>

{% endblock %}

articles/templates/articles/post_edit.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

articles/templates/articles/post_list.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    {% for post in posts %}


  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
          <center><p>  {{ post.published_date }} </p></center>
        <center><h3><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h3></center>
        <center><p>{{ post.text|linebreaksbr }}</p></center>
        <center><p><a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-primary" role="button">Parcourir</a> </p></center>
      </div>
    </div>
  </div>


<!-- OLD SIMPLE LAYOUT -->

<!--        <div class="post">-->
<!--            <div class="date">-->
<!--                {{ post.published_date }}-->
<!--            </div>-->
<!--            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>-->
<!--            <p>{{ post.text|linebreaksbr }}</p>-->
<!--        </div>-->


    {% endfor %}
{% endblock %}

backoffice/templates/backoffice/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'backoffice:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

backoffice/templates/backoffice/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'backoffice/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'backoffice:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

backoffice/templates/backoffice/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'backoffice:detail' question.id %}">Vote again?</a>